Docker support  #11
unq-arqsoft-difi/covid-back-node pull request #15
Opened 2020-06-06 04:44 UTC by fischettij

#11

2020-06-06 04:44 UTC, fischettij commented
Falta meter las credenciales en travis para que suba la imagen de docker

2020-06-06 15:19 UTC, laendoor requested changes
Hay cosas para corregir, sobre todo el Dockerfile

2020-06-06 15:19 UTC, leandrojdl commented on .travis.yml
> +  - docker build -f docker/Dockerfile -t unq-arqsoft-difi/covid-back-node .
Si no vas a hacer el push, el build per se no tiene mucho sentido. Lo unico que estás haciendo es validando que se buildee correctamente, pero no aporta demasiado. Habría que agregarle el push a docker hub.

2020-06-06 15:19 UTC, leandrojdl commented on docker/Dockerfile
> +COPY . .
No me gusta como está el dockerfile.

* en el builder te conviene copiar todos los archivos de la app (no solo package) y luego hacer la instalacion
* en yarn, para no tener problemas de cache y versiones, podes usar `yarn install --frozen-lockfile` (equivalente a `npm ci`)
* el `yarn start` del final no te va a funcionar pq estás instalando prod, o sea no hay `devdependencies` o sea no hay `nodemon` (y está bien)
* poné directamente `yarn start:production` en el CMD. Es un container de production, está bien que solo tengas cosas de prod
* el `COPY . .` está mal por dos razones. Primero porque estás copiando todo sin descriminar (incluyendo tests) y segundo porque en docker conviene usar rutas absolutas
* revisá los dockerfiles de  `devops/mercapi` y `devops/merbot` (maestri es lo sufientemente rompehuevos con estas cosas jaja)

2020-06-06 15:19 UTC, leandrojdl commented on docker/docker-compose.yml
> +    command: "yarn start:production"
podés evitar el command con lo que te puse en el dockerfile

2020-06-06 15:19 UTC, leandrojdl commented on docker/docker-compose.yml
> +version: '3.3'
probá subirla a 3.7

2020-06-06 15:19 UTC, leandrojdl commented on docker/docker-compose.yml
> +      - POSTGRES_DB=covid
tratá de ser consistente en la sintaxis. Arriba ponés las env como `ENVVAR: value`. Me gusta más esa sintaxis clave-valor que esta lista de strings

2020-06-06 15:19 UTC, leandrojdl commented on docker/docker-compose.yml
> +    #   - ./db/postgres/data:/var/lib/postgresql/data
volá el comment

2020-06-06 20:33 UTC, fischettij commented on .travis.yml
> +  - docker build -f docker/Dockerfile -t unq-arqsoft-difi/covid-back-node .
no jode que este, dejalo asi hasta que le mandemos la credenciales de dockerhub y el push

2020-06-06 20:55 UTC, fischettij commented on docker/Dockerfile
> +COPY . .
voy comentando los puntos
(con el cambio que hice ahora) los copio al final a la segunda imagen, para que los copiaría la primera?
Hecho.
El start funciona, el que no va a funcionar es `yarn dev`
Hecho, me había olvidado después de tantas pruebas jaja
Es verdad copiaba todo, ya lo cambie
Ahora me da paja tener que conectarme a la vpn, pero los voy a revisar

2020-06-06 20:55 UTC, fischettij commented on docker/docker-compose.yml
> +    command: "yarn start:production"
lo estaba usando para pruebas, ya lo vole

2020-06-06 22:30 UTC, fischettij commented on docker/docker-compose.yml
> +      - POSTGRES_DB=covid
hecho

2020-06-06 22:30 UTC, fischettij commented on docker/docker-compose.yml
> +version: '3.3'
hecho

2020-06-06 22:30 UTC, fischettij commented on docker/docker-compose.yml
> +    #   - ./db/postgres/data:/var/lib/postgresql/data
hecho, si te llego a joder la persistencia, es por permisos. De ultima para pruebas locales comentalo

2020-06-07 01:07 UTC, laendoor approved these changes

2020-06-07 01:07 UTC, merged