Test Support, CI, Coverage
unq-arqsoft-difi/covid-back-node pull request #3
Opened 2020-04-26 17:27 UTC by fischettij

Agregue:
- Soporte para test del api (se puede mejorar mas adelante con apis de verdad pero la básico esta)
- Integración con Tracis
- Integración con coveralls

2020-04-26 19:19 UTC, laendoor requested changes

2020-04-26 19:19 UTC, leandrojdl commented on package.json
> +    "test": "NODE_ENV=test jest --verbose",
en el tests ya estás importando el file `.env.test`, dejá las variables ahí (se puede trackear siempre que no haya data sensible) y sacalas de los comandos.

2020-04-26 19:19 UTC, leandrojdl commented on package.json
> +    "test:coverage": "NODE_ENV=test jest --coverage"
este hace lo mismo que `test:ci`. Quizás lo que podés hacer es:

```json
"test:ci": "jest --verbose --coverage",
"coveralls": "coveralls < coverage/lcov.info"
```

y en el `.travis.yml`

```yaml
script: yarn test:ci
after_script: yarn coveralls
```

2020-04-26 19:19 UTC, leandrojdl commented on test/server.test.js
> +})
Si es para probar, ok. Pero si es para tener un tests de errores, no tiene mucho sentido. Vas a querer probar los 4xx en cada endpoint para verificar algún dato que vuelva inválido el request. El nombre del tests no es muy reprresentativo tampoco.

2020-04-26 19:19 UTC, leandrojdl commented on .travis.yml
> +  - yarn install
Probalo, pero creo que el `yarn install` lo podés omitir. No recuerdo bien, pero creo que por lo menos con `npm` lo hacía automático en travis. Pero fijate pq no estoy 100% seguro.

Lo que podés agregar en el `before_script` es el `yarn run lint`

2020-04-26 19:19 UTC, leandrojdl commented on test/jest-extensions.js
> +const Ajv = require('ajv');
Fijate si realmente lo necesitás. Yo creo que en este tipo de API no hace falta usar Ajv.

2020-05-01 20:20 UTC, fischettij commented on test/server.test.js
> +})
Lo agregué por que esa parte del código en el server.js no estaba cubierta. Es para el handling de rutas no encontradas

2020-05-02 01:27 UTC, laendoor approved these changes

2020-05-02 01:29 UTC, merged